#!/bin/bash
# Gradle wrapper script
# Generated by Gradle wrapper

# Determine the directory of the script
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
GRADLE_WRAPPER_JAR="$SCRIPT_DIR/gradle/wrapper/gradle-wrapper.jar"
GRADLE_WRAPPER_PROPERTIES="$SCRIPT_DIR/gradle/wrapper/gradle-wrapper.properties"

# Check if wrapper jar exists
if [ ! -f "$GRADLE_WRAPPER_JAR" ]; then
    echo "Gradle wrapper jar not found at $GRADLE_WRAPPER_JAR"
    exit 1
fi

# Extract Gradle version from properties
GRADLE_VERSION=$(grep -E "^distributionUrl=" "$GRADLE_WRAPPER_PROPERTIES" | cut -d'=' -f2 | sed 's/.*gradle-\([0-9.]*\)-bin\.zip/\1/')

if [ -z "$GRADLE_VERSION" ]; then
    echo "Could not determine Gradle version from wrapper properties"
    exit 1
fi

# Download Gradle distribution if not already cached
GRADLE_HOME="${HOME}/.gradle/wrapper/dists/gradle-${GRADLE_VERSION}-bin"
if [ ! -d "$GRADLE_HOME" ]; then
    echo "Downloading Gradle ${GRADLE_VERSION}..."
    mkdir -p "$GRADLE_HOME"
    DIST_URL=$(grep -E "^distributionUrl=" "$GRADLE_WRAPPER_PROPERTIES" | cut -d'=' -f2)
    curl -fSL "$DIST_URL" -o /tmp/gradle-${GRADLE_VERSION}-bin.zip
    unzip -q /tmp/gradle-${GRADLE_VERSION}-bin.zip -d "$GRADLE_HOME"
    rm /tmp/gradle-${GRADLE_VERSION}-bin.zip
fi

# Find the actual unpacked directory (Gradle creates a subdirectory with a random hash)
GRADLE_BIN_DIR=$(find "$GRADLE_HOME" -name "gradle-${GRADLE_VERSION}" -type d | head -n1)
if [ -z "$GRADLE_BIN_DIR" ]; then
    echo "Gradle installation not found in $GRADLE_HOME"
    exit 1
fi

# Execute Gradle
"$GRADLE_BIN_DIR/bin/gradle" "$@"
